# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(833, 530)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.titlelabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.titlelabel.setGeometry(QtCore.QRect(60, 20, 341, 51))
        self.titlelabel.setObjectName("titlelabel")
        self.ShowPNGpushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.ShowPNGpushButton.setGeometry(QtCore.QRect(92, 120, 121, 28))
        self.ShowPNGpushButton.setObjectName("ShowPNGpushButton")
        self.ShowGIFpushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.ShowGIFpushButton.setGeometry(QtCore.QRect(240, 120, 131, 28))
        self.ShowGIFpushButton.setObjectName("ShowGIFpushButton")
        self.imagelabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.imagelabel.setGeometry(QtCore.QRect(90, 160, 541, 231))
        self.imagelabel.setText("")
        self.imagelabel.setPixmap(QtGui.QPixmap("Image/picture.jpg"))
        self.imagelabel.setScaledContents(True)
        self.imagelabel.setObjectName("imagelabel")
        self.FontsizepushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.FontsizepushButton.setGeometry(QtCore.QRect(192, 72, 93, 28))
        self.FontsizepushButton.setObjectName("FontsizepushButton")
        self.AlignLeftPushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.AlignLeftPushButton.setGeometry(QtCore.QRect(292, 72, 93, 28))
        self.AlignLeftPushButton.setObjectName("AlignLeftPushButton")
        self.ChangetextpushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.ChangetextpushButton.setGeometry(QtCore.QRect(92, 72, 93, 28))
        self.ChangetextpushButton.setObjectName("ChangetextpushButton")
        self.AlignRightPushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.AlignRightPushButton.setGeometry(QtCore.QRect(492, 72, 93, 28))
        self.AlignRightPushButton.setObjectName("AlignRightPushButton")
        self.AlignCenterPushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.AlignCenterPushButton.setGeometry(QtCore.QRect(392, 72, 93, 28))
        self.AlignCenterPushButton.setObjectName("AlignCenterPushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 833, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.titlelabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600; color:#ff0000;\">Nguyễn Huỳnh Yến Nhi</span></p></body></html>"))
        self.ShowPNGpushButton.setText(_translate("MainWindow", "Show .PNG format"))
        self.ShowGIFpushButton.setText(_translate("MainWindow", "Show .Gif format"))
        self.FontsizepushButton.setText(_translate("MainWindow", "Font Size ++"))
        self.AlignLeftPushButton.setText(_translate("MainWindow", "Align Left"))
        self.ChangetextpushButton.setText(_translate("MainWindow", "Change Text"))
        self.AlignRightPushButton.setText(_translate("MainWindow", "Align Right"))
        self.AlignCenterPushButton.setText(_translate("MainWindow", "Align Center"))
