# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(648, 470)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(160, 20, 371, 61))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 80, 101, 31))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(30, 130, 101, 31))
        self.label_3.setObjectName("label_3")
        self.lineEditFullname = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEditFullname.setGeometry(QtCore.QRect(140, 80, 351, 31))
        self.lineEditFullname.setObjectName("lineEditFullname")
        self.lineEditMail = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEditMail.setGeometry(QtCore.QRect(140, 130, 351, 31))
        self.lineEditMail.setObjectName("lineEditMail")
        self.checkML = QtWidgets.QCheckBox(parent=self.centralwidget)
        self.checkML.setGeometry(QtCore.QRect(140, 190, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkML.setFont(font)
        self.checkML.setObjectName("checkML")
        self.checkSC = QtWidgets.QCheckBox(parent=self.centralwidget)
        self.checkSC.setGeometry(QtCore.QRect(140, 230, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkSC.setFont(font)
        self.checkSC.setObjectName("checkSC")
        self.checkBox_3 = QtWidgets.QCheckBox(parent=self.centralwidget)
        self.checkBox_3.setGeometry(QtCore.QRect(140, 270, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_3.setFont(font)
        self.checkBox_3.setObjectName("checkBox_3")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(140, 170, 221, 31))
        self.label_4.setObjectName("label_4")
        self.pushButtonSubmit = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonSubmit.setGeometry(QtCore.QRect(240, 310, 93, 28))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("tick-512.webp"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonSubmit.setIcon(icon)
        self.pushButtonSubmit.setObjectName("pushButtonSubmit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 648, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:600; color:#5500ff;\">Course Registration</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Full Name:</span></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Email:</span></p></body></html>"))
        self.checkML.setText(_translate("MainWindow", "Machine Learning"))
        self.checkSC.setText(_translate("MainWindow", "Deep learning"))
        self.checkBox_3.setText(_translate("MainWindow", "Smart Contract"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600; color:#ff007f;\">Course Section:</span></p></body></html>"))
        self.pushButtonSubmit.setText(_translate("MainWindow", "Submit"))
