
print(list(range(5)))                
print(list(range(5, 10)))            
print(list(range(5, 20, 3)))         
print(list(range(20, 5, -1)))       
print(list(range(20, 5, -3)))       
print(list(range(10, 5)))           
print(list(range(0)))           
print(list(range(10, 101, 10)))      
print(list(range(10, -1, -1)))       
print(list(range(-3, 4)))            
print(list(range(0, 10, 1)))     
