# Form implementation generated from reading ui file 'MyQMainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 20, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(60, 70, 441, 41))
        self.lineEdit.setObjectName("lineEdit")
        self.push_sent = QtWidgets.QPushButton(parent=self.centralwidget)
        self.push_sent.setGeometry(QtCore.QRect(60, 130, 93, 28))
        self.push_sent.setObjectName("push_sent")
        self.push_visit = QtWidgets.QPushButton(parent=self.centralwidget)
        self.push_visit.setGeometry(QtCore.QRect(180, 130, 93, 28))
        self.push_visit.setObjectName("push_visit")
        self.push_exit = QtWidgets.QPushButton(parent=self.centralwidget)
        self.push_exit.setGeometry(QtCore.QRect(290, 130, 93, 28))
        self.push_exit.setObjectName("push_exit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Your Name: "))
        self.push_sent.setText(_translate("MainWindow", "Send"))
        self.push_visit.setText(_translate("MainWindow", "Visit Blog"))
        self.push_exit.setText(_translate("MainWindow", "Exit"))
